### PR TITLE
Added relevant folders

### PR DESCRIPTION
**Pull request by gauravvv2204**

### CODE REVIEW

**Comment by ritikrajdev** [comment]
@gauravvv2204 can you please do them in relevant folders. :smile:

**Comment by gauravvv2204** [comment]
conflict ho gya 😢

**Comment by ritikrajdev** [comment]
My Bad thought it to be UTA015 :joy: 
I apologize for the thing.

**Comment by ritikrajdev** [comment]
Thanks for the Contribution :wink:

**Pull request merged**
